services:
  backend:
    build: ./cazss-backend
    container_name: cazss-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
    networks:
      - cazss-net
    depends_on:
      - mysql

  frontend:
    build: ./cazss-frontend
    container_name: cazss-frontend
    restart: unless-stopped
    networks:
      - cazss-net

  mysql:
    image: mysql:8.2
    container_name: cazss-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cazss-net
    ports:
      - "${MYSQL_HOST_PORT}:3306"

  nginx:
    image: nginx:latest
    container_name: cazss-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cazss-net
    depends_on:
      - frontend
      - backend

networks:
  cazss-net:
    driver: bridge

volumes:
  mysql-data:
